name: Chocolatey Release

on:
  workflow_run:
    workflows: ["Github Release"]
    types:
      - completed

jobs:
  check-secrets:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      has-api-key: ${{ steps.check-api-key.outputs.has-api-key }}
    steps:
      - id: check-api-key
        env:
          CHOCO_KEY_EXISTS: ${{ secrets.CHOCO_API_KEY != '' }}
        run: |
          if [[ "$CHOCO_KEY_EXISTS" == "true" ]]; then
            echo "has-api-key=true" >> $GITHUB_OUTPUT
          else
            echo "has-api-key=false" >> $GITHUB_OUTPUT
            echo "::warning::CHOCO_API_KEY is not available. Skipping Chocolatey package update."
          fi

  publish-chocolatey:
    needs: check-secrets
    if: needs.check-secrets.outputs.has-api-key == 'true'
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        shell: bash
        run: |
          # Install Git LFS on Windows
          git lfs install

      - name: Get release details
        id: release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Debug: List all releases
          echo "Listing all releases:"
          gh release list

          # Get the latest release with more robust error handling
          RELEASE_INFO=$(gh release list --limit 1 || echo "")
          if [ -z "$RELEASE_INFO" ]; then
            echo "No releases found. Exiting workflow."
            exit 1
          fi

          # Debug: Print release info
          echo "Release Info: $RELEASE_INFO"

          # Get the tag directly from the GitHub CLI
          TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "Extracted TAG: $TAG"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

          # Download release notes
          echo "Downloading release notes..."
          gh release view $TAG --json body -q '.body' > RELEASE_NOTES.txt
          echo "Release notes downloaded successfully."

      - name: Download release artifacts
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $TAG = "${{ steps.release.outputs.TAG }}"
          Write-Host "Using TAG: $TAG for downloading artifacts"

          if ([string]::IsNullOrEmpty($TAG)) {
            Write-Host "Error: Empty tag detected. Cannot download release artifacts."
            exit 1
          }

          mkdir -p choco-pkg/tools

          Write-Host "Downloading gv-windows.exe.zip..."
          gh release download $TAG -p "gv-windows.exe.zip" -D ./choco-pkg/tools

          if (-not $?) {
            Write-Host "Failed to download gv-windows.exe.zip"
            exit 1
          }

          # Download the release notes file
          Write-Host "Copying release notes to package..."
          Copy-Item -Path "${{ github.workspace }}/RELEASE_NOTES.txt" -Destination "choco-pkg/tools/RELEASE_NOTES.txt"

          Write-Host "Release artifacts downloaded successfully."

      - name: Generate Chocolatey package files
        shell: powershell
        run: |
          $version = "${{ steps.release.outputs.VERSION }}"

          # Copy LICENSE to the tools directory
          Copy-Item -Path "${{ github.workspace }}/LICENSE" -Destination "choco-pkg/tools/LICENSE"

          # Extract the zip file first
          $zipFile = Get-ChildItem -Path ".\choco-pkg\tools" -Filter "gv-windows.exe.zip" | Select-Object -First 1 -ExpandProperty FullName
          if ($zipFile) {
            Write-Host "Extracting $zipFile..."
            Expand-Archive -Path $zipFile -DestinationPath ".\choco-pkg\tools" -Force
          } else {
            Write-Host "ERROR: gv-windows.exe.zip not found in tools directory!"
          }

          # Create nuspec file
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
            <metadata>
              <id>gv</id>
              <version>$version</version>
              <title>Git Vault (gv)</title>
              <authors>zackiles</authors>
              <projectUrl>https://github.com/zackiles/git-vault</projectUrl>
              <projectSourceUrl>https://github.com/zackiles/git-vault</projectSourceUrl>
              <docsUrl>https://github.com/zackiles/git-vault/blob/main/README.md</docsUrl>
              <iconUrl>https://github.com/zackiles/git-vault/blob/main/logo.ico</iconUrl>
              <bugTrackerUrl>https://github.com/zackiles/git-vault/issues</bugTrackerUrl>
              <licenseUrl>https://github.com/zackiles/git-vault/blob/main/LICENSE</licenseUrl>
              <license type="file">tools\LICENSE</license>
              <releaseNotes>tools\RELEASE_NOTES.txt</releaseNotes>
              <requireLicenseAcceptance>true</requireLicenseAcceptance>
              <description>Commit your secrets safely and effortlessly with Git using GPG. 1Password supported. Transparently encrypts files or folder on commit, decrypts on checkout. Handles Git LFS automatically for large files.</description>
              <summary>Easiest way to encrypt/decrypt files or folders in your git repository.</summary>
            </metadata>
            <files>
              <file src="tools\**" target="tools" />
            </files>
          </package>
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\gv.nuspec

          # Create chocolateyInstall.ps1
          @"
          `$ErrorActionPreference = 'Stop'

          `$toolsDir = "`$(Split-Path -Parent `$MyInvocation.MyCommand.Definition)"
          `$zipFile = Get-ChildItem -Path `$toolsDir -Filter "gv-windows.exe.zip" | Select-Object -First 1 -ExpandProperty FullName

          `$packageArgs = @{
            packageName    = 'gv'
            unzipLocation  = `$toolsDir
            file           = `$zipFile
          }

          Get-ChocolateyUnzip @packageArgs

          # Copy the binary file to both gv.exe and git-vault.exe for compatibility
          `$exeFile = Get-ChildItem -Path `$toolsDir -Filter "gv-x86_64-pc-windows-msvc.exe" | Select-Object -First 1 -ExpandProperty FullName
          if (-not `$exeFile) {
            `$exeFile = Get-ChildItem -Path `$toolsDir -Filter "gv-windows.exe" | Select-Object -First 1 -ExpandProperty FullName
          }

          # Create primary command as gv.exe
          Copy-Item -Path `$exeFile -Destination (Join-Path `$toolsDir "gv.exe") -Force
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\tools\chocolateyInstall.ps1

          # Create verification file
          @"
          VERIFICATION
          Verification is intended to assist the Chocolatey moderators and community
          in verifying that this package's contents are trustworthy.

          This package is published by the git-vault project itself. The binaries are
          identical to those in the released zip files from the official GitHub releases.

          Package Source: https://github.com/zackiles/git-vault
          Release URL: https://github.com/zackiles/git-vault/releases/tag/v$version

          To verify the binary:

          1. Download the official release from the URL above
          2. Generate a checksum using:
             - PowerShell: Get-FileHash -Algorithm SHA256 gv.exe
             - Command Prompt: certutil -hashfile gv.exe SHA256

          3. Compare the checksum with:
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\tools\VERIFICATION.txt

          # List files to debug
          Write-Host "Files in choco-pkg/tools:"
          Get-ChildItem -Path ".\choco-pkg\tools" -Recurse | Format-Table Name, Length -AutoSize

          # Calculate and append checksum - look for exe files in all subdirectories
          $exePath = Get-ChildItem -Path ".\choco-pkg\tools" -Recurse -Filter "*.exe" | Where-Object { -not $_.PSIsContainer } | Select-Object -First 1 -ExpandProperty FullName
          if ($exePath) {
            Write-Host "Found executable: $exePath"
            $hash = Get-FileHash -Path $exePath -Algorithm SHA256
            Add-Content -Path .\choco-pkg\tools\VERIFICATION.txt -Value "SHA256: $($hash.Hash)"
          } else {
            Write-Host "ERROR: No .exe files found in tools directory or subdirectories!"
            # Add a placeholder hash so the build doesn't fail
            Add-Content -Path .\choco-pkg\tools\VERIFICATION.txt -Value "SHA256: 0000000000000000000000000000000000000000000000000000000000000000"
            Write-Host "Added placeholder hash to VERIFICATION.txt to avoid build failure."
          }

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Build Chocolatey package
        shell: powershell
        run: |
          cd choco-pkg
          choco pack gv.nuspec

      - name: Push to Chocolatey.org
        if: success()
        shell: powershell
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          cd choco-pkg
          # Use the API key from secrets
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          # Push the package
          choco push gv.${{ steps.release.outputs.VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key $env:CHOCO_API_KEY
