name: Update Chocolatey Package

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  check-secrets:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      has-api-key: ${{ steps.check-api-key.outputs.has-api-key }}
    steps:
      - id: check-api-key
        env:
          CHOCO_KEY_EXISTS: ${{ secrets.CHOCO_API_KEY != '' }}
        run: |
          if [[ "$CHOCO_KEY_EXISTS" == "true" ]]; then
            echo "has-api-key=true" >> $GITHUB_OUTPUT
          else
            echo "has-api-key=false" >> $GITHUB_OUTPUT
            echo "::warning::CHOCO_API_KEY is not available. Skipping Chocolatey package update."
          fi

  publish-chocolatey:
    needs: check-secrets
    if: needs.check-secrets.outputs.has-api-key == 'true'
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get release details
        id: release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Debug: List all releases
          echo "Listing all releases:"
          gh release list

          # Get the latest release with more robust error handling
          RELEASE_INFO=$(gh release list --limit 1 || echo "")
          if [ -z "$RELEASE_INFO" ]; then
            echo "No releases found. Exiting workflow."
            exit 1
          fi

          # Debug: Print release info
          echo "Release Info: $RELEASE_INFO"

          # Get the tag directly from the GitHub CLI
          TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "Extracted TAG: $TAG"
          VERSION="${TAG#v}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Download release artifacts
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $TAG = "${{ steps.release.outputs.TAG }}"
          Write-Host "Using TAG: $TAG for downloading artifacts"

          if ([string]::IsNullOrEmpty($TAG)) {
            Write-Host "Error: Empty tag detected. Cannot download release artifacts."
            exit 1
          }

          mkdir -p choco-pkg/tools

          Write-Host "Downloading gv-windows.exe.zip..."
          gh release download $TAG -p "gv-windows.exe.zip" -D ./choco-pkg/tools

          if (-not $?) {
            Write-Host "Failed to download gv-windows.exe.zip"
            exit 1
          }

          Write-Host "Release artifacts downloaded successfully."

      - name: Generate Chocolatey package files
        shell: powershell
        run: |
          $version = "${{ steps.release.outputs.VERSION }}"

          # Create nuspec file
          @"
          <?xml version="1.0" encoding="utf-8"?>
          <package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
            <metadata>
              <id>gv</id>
              <version>$version</version>
              <title>Git Vault (gv)</title>
              <authors>zackiles</authors>
              <projectUrl>https://github.com/zackiles/git-vault</projectUrl>
              <licenseUrl>https://github.com/zackiles/git-vault/blob/main/LICENSE</licenseUrl>
              <requireLicenseAcceptance>false</requireLicenseAcceptance>
              <description>Drop-dead simple solution for sharing sensitive things in git repositories</description>
              <tags>git security secrets vault encryption</tags>
            </metadata>
            <files>
              <file src="tools\**" target="tools" />
            </files>
          </package>
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\gv.nuspec

          # Create chocolateyInstall.ps1
          @"
          `$ErrorActionPreference = 'Stop'

          `$toolsDir = "`$(Split-Path -Parent `$MyInvocation.MyCommand.Definition)"
          `$zipFile = Get-ChildItem -Path `$toolsDir -Filter "gv-windows.exe.zip" | Select-Object -First 1 -ExpandProperty FullName

          `$packageArgs = @{
            packageName    = 'gv'
            unzipLocation  = `$toolsDir
            file           = `$zipFile
          }

          Get-ChocolateyUnzip @packageArgs

          # Copy the binary file to both gv.exe and git-vault.exe for compatibility
          `$exeFile = Get-ChildItem -Path `$toolsDir -Filter "gv-x86_64-pc-windows-msvc.exe" | Select-Object -First 1 -ExpandProperty FullName
          if (-not `$exeFile) {
            `$exeFile = Get-ChildItem -Path `$toolsDir -Filter "gv-windows.exe" | Select-Object -First 1 -ExpandProperty FullName
          }

          # Create primary command as gv.exe
          Copy-Item -Path `$exeFile -Destination (Join-Path `$toolsDir "gv.exe") -Force

          # Also create git-vault.exe as an alias
          Copy-Item -Path `$exeFile -Destination (Join-Path `$toolsDir "git-vault.exe") -Force
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\tools\chocolateyInstall.ps1

          # Create verification file
          @"
          VERIFICATION
          Verification is intended to assist the Chocolatey moderators and community
          in verifying that this package's contents are trustworthy.

          This package is published by the git-vault project itself. The binaries are
          identical to those in the released zip files from the official GitHub releases.

          URL: https://github.com/zackiles/git-vault/releases/tag/v$version
          "@ | Out-File -Encoding utf8 -FilePath .\choco-pkg\tools\VERIFICATION.txt

      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      - name: Build Chocolatey package
        shell: powershell
        run: |
          cd choco-pkg
          choco pack gv.nuspec

      - name: Push to Chocolatey.org
        if: success()
        shell: powershell
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        run: |
          cd choco-pkg
          # Use the API key from secrets
          choco apikey --key $env:CHOCO_API_KEY --source https://push.chocolatey.org/
          # Push the package
          choco push gv.${{ steps.release.outputs.VERSION }}.nupkg --source https://push.chocolatey.org/ --api-key $env:CHOCO_API_KEY
